name: wiki_vault
description: WikiVault-Project for Flutter Course

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  flutter_launcher_icons: ^0.10.0
  flutter_html: ^3.0.0-alpha.6
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.4.1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon_adaptive_fore.png"
  adaptive_icon_background: "assets/icon_adaptive_back.png"